# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.7'

services:
  postgresql:
    image: postgres:13.4
    # If you want to relocate the postgres data (volume) to your local directory, uncomment the lines below
    # volumes:
    #   - ~/volumes/entando-bundle-cli/%BUNDLENAME%/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=%BUNDLENAME%-user
      - POSTGRES_PASSWORD=%BUNDLENAME%-password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=%BUNDLENAME%
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
