export const RESOURCES_FOLDER = 'resources'
export const CONFIG_FOLDER = '.entando'
export const SVC_FOLDER = 'svc'
export const BUNDLE_DESCRIPTOR_FILE_NAME = 'entando.json'
export const CONFIG_FILE = 'config.json'
export const DEFAULT_CONFIG_FILE = 'default-config.json'
export const OUTPUT_FOLDER = [CONFIG_FOLDER, 'output']
export const LOGS_FOLDER = [CONFIG_FOLDER, 'logs']
export const DOCKER_CONFIG_FOLDER = [CONFIG_FOLDER, 'docker']
export const DESCRIPTORS_OUTPUT_FOLDER = [...OUTPUT_FOLDER, 'descriptors']
export const EPC_FOLDER = 'epc'
export const MICROFRONTENDS_FOLDER = 'microfrontends'
export const MICROSERVICES_FOLDER = 'microservices'
export const WIDGETS_FOLDER = 'widgets'
export const PLUGINS_FOLDER = 'plugins'
export const BUILD_FOLDER = 'build'
export const DESCRIPTOR_EXTENSION = '.yaml'
