export const RESOURCES_FOLDER = 'resources'
export const CONFIG_FOLDER = '.ent'
export const TMP_TEST_FOLDER = 'entando-bundle-cli-test'
export const CONFIG_FILE = 'config.json'
export const DEFAULT_CONFIG_FILE = 'default-config.json'
