export const RESOURCES_FOLDER = 'resources'
export const CONFIG_FOLDER = '.entando'
export const AUX_FOLDER = 'aux'
export const BUNDLE_DESCRIPTOR_FILE_NAME = 'entando.json'
export const CONFIG_FILE = 'config.json'
export const DEFAULT_CONFIG_FILE = 'default-config.json'
export const OUTPUT_FOLDER = [CONFIG_FOLDER, 'output']
export const DESCRIPTORS_OUTPUT_FOLDER = [...OUTPUT_FOLDER, 'descriptors']
export const EPC_FOLDER = 'epc'
export const MICROFRONTENDS_FOLDER = 'microfrontends'
export const MICROSERVICES_FOLDER = 'microservices'
export const WIDGETS_FOLDER = 'widgets'
export const DIST_FOLDER = 'dist'
